version: '3.8'

services:
  synthetic-monitor:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-2
      - S3_BUCKET=test-bucket
      - PROMETHEUS_PUSHGATEWAY=http://pushgateway:9091
      - TEST_URL=${TEST_URL}
      - ZAP_API_URL=http://zap:8080
    volumes:
      - ./zap-results:/app/zap-results
    depends_on:
      - zap
      - pushgateway
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
      MINIO_REGION_NAME: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - pushgateway

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ./zap-results:/zap/wrk:rw
    environment:
      - JAVA_OPTS=-Xmx512m -Djava.awt.headless=true
    command: [
      "zap-x.sh", 
      "-daemon",
      "-host", "0.0.0.0",
      "-port", "8080",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true",
      "-config", "api.disablekey=true",
      "-config", "database.recoverylog=false",
      "-config", "connection.timeoutInSecs=60",
      "-nostartup"
    ]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/JSON/core/view/version/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  minio_data:
  prometheus_data: