version: '3.8'

services:
  synthetic-monitor:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-2
      - S3_BUCKET=test-bucket
      - PROMETHEUS_PUSHGATEWAY=http://pushgateway:9091
      - TEST_URL=${TEST_URL}
      - ZAP_API_URL=http://zap:8080
    volumes:
      - ./zap-results:/app/zap-results
    depends_on:
      - zap
      - pushgateway
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
      MINIO_REGION_NAME: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ./zap-results:/zap/wrk
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true"]
    ports:
      - "8080:8080"

volumes:
  minio_data: