version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
      MINIO_REGION_NAME: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  zap:
    image: ghcr.io/zaproxy/zaproxy:weekly
    ports:
      - "8080:8080"
    environment:
      - ZAP_PORT=8080
      - JAVA_OPTS="-Xmx4096m"
    user: zap
    command: zap.sh -daemon -port 8080 -host 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - zap-network

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - zap-network

volumes:
  minio_data:
  zap_data:

networks:
  zap-network:
    driver: bridge