import type { Logger } from "@insightview/observability";
import type { EventBus, RepeatingJobScheduler } from "@insightview/event-bus";
import {
  Topics,
  defaultTenant,
  type CheckScheduledPayload,
} from "@insightview/core";
import { listEnabledChecks } from "@insightview/db";

export interface ScheduleLoopOpts {
  bus: EventBus;
  scheduler: RepeatingJobScheduler;
  log: Logger;
  isLeader: () => boolean;
  intervalMs?: number;
}

/**
 * Reconcile-from-DB loop. Every N seconds, the leader reads the set of
 * enabled checks from Postgres and upserts their cron schedules into the
 * RepeatingJobScheduler. BullMQ handles the actual cron firing; this loop
 * just keeps the scheduler's registry in sync with the source of truth.
 *
 * When a cron fires, BullMQ emits a CheckScheduled message to the
 * `checks.scheduled` topic which the runner consumes. We do NOT create a
 * CheckRun row in this loop — that happens in the runner's claim step,
 * using the envelope's payload.runId (generated by the cron wrapper below).
 */
export function startScheduleLoop(opts: ScheduleLoopOpts): () => void {
  const interval = opts.intervalMs ?? 15_000;
  let stopped = false;
  const knownSchedules = new Set<string>();

  const tick = async () => {
    if (stopped) return;
    if (!opts.isLeader()) return;

    try {
      const ctx = defaultTenant("scheduler");
      const checks = await listEnabledChecks(ctx);
      const seen = new Set<string>();
      for (const check of checks) {
        const key = `check:${check.tenantId}:${check.id}`;
        seen.add(key);
        const payloadTemplate: CheckScheduledPayload = {
          runId: "__TEMPLATE__", // The cron wrapper replaces this at fire time
          checkId: check.id,
          checkName: check.name,
          scheduledAt: new Date(0).toISOString(),
          targetUrl: check.targetUrl,
          scriptRef: check.scriptRef,
          timeoutMs: check.timeoutMs,
          retries: check.retries,
          triggeredBy: "SCHEDULE",
          assertions:
            (check.assertions as Array<{ type: string; value: string }>) ?? [],
        };
        try {
          await opts.scheduler.upsertSchedule({
            key,
            topic: Topics.ChecksScheduled,
            cron: check.schedule,
            payload: payloadTemplate,
            tenantId: check.tenantId,
          });
          knownSchedules.add(key);
        } catch (err) {
          opts.log.warn({ err, check: check.name }, "failed to upsert schedule");
        }
      }

      // Remove schedules whose checks are no longer enabled.
      for (const key of knownSchedules) {
        if (!seen.has(key)) {
          try {
            await opts.scheduler.removeSchedule(key);
            knownSchedules.delete(key);
            opts.log.info({ key }, "removed stale schedule");
          } catch (err) {
            opts.log.warn({ err, key }, "failed to remove schedule");
          }
        }
      }
    } catch (err) {
      opts.log.error({ err }, "schedule loop tick failed");
    }
  };

  const handle = setInterval(() => void tick(), interval);
  // Trigger first tick quickly after leadership is acquired.
  setTimeout(() => void tick(), 1000);

  return () => {
    stopped = true;
    clearInterval(handle);
  };
}
