name: 'Setup ZAP'
description: 'Sets up and configures OWASP ZAP for security scanning'

inputs:
  zap-api-url:
    description: 'ZAP API URL'
    required: false
    default: 'http://localhost:8080'
  max-retries:
    description: 'Maximum number of retries for ZAP readiness check'
    required: false
    default: '30'

outputs:
  zap-status:
    description: 'Status of ZAP setup'
    value: ${{ steps.verify-zap.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Start ZAP
      shell: bash
      run: |
        docker run -d \
          --name zap \
          -p 8080:8080 \
          -e JAVA_OPTS="-Xms512m -Xmx4096m" \
          owasp/zap2docker-stable:latest \
          zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true

    - name: Verify ZAP readiness
      id: verify-zap
      shell: bash
      run: |
        echo "Waiting for ZAP to be ready..."
        attempt=1
        max_attempts=${{ inputs.max-retries }}
        until curl -sf ${{ inputs.zap-api-url }}/ > /dev/null; do
          if [ $attempt -eq $max_attempts ]; then
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "ZAP failed to start after $max_attempts attempts"
            docker logs zap
            exit 1
          fi
          echo "Attempt $attempt: ZAP not ready, waiting..."
          sleep 2
          attempt=$((attempt + 1))
        done
        echo "status=ready" >> $GITHUB_OUTPUT
        echo "ZAP is ready"

    - name: Configure ZAP
      shell: bash
      run: |
        # Core settings
        curl -sf "${{ inputs.zap-api-url }}/JSON/core/action/setOptionDefaultUserAgent/?String=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20Chrome/120.0.0.0%20Safari/537.36"
        curl -sf "${{ inputs.zap-api-url }}/JSON/core/action/setOptionHttpStateEnabled/?boolean=true"
        curl -sf "${{ inputs.zap-api-url }}/JSON/core/action/setOptionTimeoutInSecs/?Integer=120"
        
        # Spider settings
        curl -sf "${{ inputs.zap-api-url }}/JSON/spider/action/setOptionMaxDuration/?Integer=60"
        curl -sf "${{ inputs.zap-api-url }}/JSON/spider/action/setOptionMaxParseSizeBytes/?Integer=10485760"
        
        # Performance settings
        curl -sf "${{ inputs.zap-api-url }}/JSON/core/action/setOptionThreadPerHost/?Integer=4"
        curl -sf "${{ inputs.zap-api-url }}/JSON/ascan/action/setOptionThreadPerHost/?Integer=4"