name: Synthetic Monitoring

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering
    inputs:
      test_url:
        description: 'Target URL to test'
        required: false
        type: string
      browser:
        description: 'Browser to test with'
        required: false
        type: choice
        options:
          - chromium
          - mobile-chrome
        default: 'chromium'
      env_vars:
        description: 'Additional environment variables (JSON)'
        required: false
        type: string
        default: '{}'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  S3_FORCE_PATH_STYLE: ${{ secrets.S3_FORCE_PATH_STYLE }}
  S3_TLS_VERIFY: ${{ secrets.S3_TLS_VERIFY }}
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  PROMETHEUS_PUSHGATEWAY: ${{ secrets.PROMETHEUS_PUSHGATEWAY }}
  TEST_URL: ${{ inputs.test_url || secrets.TEST_URL }}

jobs:
  synthetic-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.0-jammy
    
    steps:
      - uses: actions/checkout@v4

      - name: Run Synthetic Monitoring
        uses: ./
        with:
          test_url: ${{ env.TEST_URL }}
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          s3_bucket: ${{ env.S3_BUCKET }}
          s3_endpoint: ${{ env.S3_ENDPOINT || env.MINIO_ENDPOINT }}
          s3_force_path_style: ${{ env.S3_FORCE_PATH_STYLE || 'true' }}
          s3_tls_verify: ${{ env.S3_TLS_VERIFY || 'false' }}
          minio_access_key: ${{ env.MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ env.MINIO_SECRET_KEY }}
          minio_root_user: ${{ env.MINIO_ROOT_USER }}
          minio_root_password: ${{ env.MINIO_ROOT_PASSWORD }}
          minio_endpoint: ${{ env.MINIO_ENDPOINT }}
          prometheus_pushgateway: ${{ env.PROMETHEUS_PUSHGATEWAY }}
          browser: ${{ inputs.browser || 'chromium' }}
          env_vars: ${{ inputs.env_vars }}