name: Synthetic Monitoring

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering
    inputs:
      test_url:
        description: 'Target URL to test'
        required: false
        type: string
      browser:
        description: 'Browser to test with'
        required: false
        type: choice
        options:
          - chromium
          - mobile-chrome
        default: 'chromium'
      env_vars:
        description: 'Additional environment variables (JSON)'
        required: false
        type: string
        default: '{}'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  PROMETHEUS_PUSHGATEWAY: ${{ secrets.PROMETHEUS_PUSHGATEWAY }}
  TEST_URL: ${{ inputs.test_url || secrets.TEST_URL }}

jobs:
  synthetic-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-focal
    permissions:
      contents: read
      security-events: write
      actions: read
    continue-on-error: true  # Allow the workflow to continue even if this job fails
    
    steps:
      - uses: actions/checkout@v4

      - name: Run Synthetic Monitoring
        id: synthetic
        uses: ./.github/actions/synthetic-monitoring
        continue-on-error: true # Allow the step to fail but still run the remaining workflow
        with:
          test_url: ${{ env.TEST_URL }}
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          s3_bucket: ${{ env.S3_BUCKET }}
          prometheus_pushgateway: ${{ env.PROMETHEUS_PUSHGATEWAY }}
          browser: ${{ inputs.browser || 'chromium' }}
          env_vars: ${{ inputs.env_vars }}
          
      - name: Report Status
        if: steps.synthetic.outcome != 'success'
        run: echo "::warning::Synthetic monitoring tests failed, but workflow will continue"

  zap-scan:
    # Runs independently from synthetic-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        continue-on-error: true
        with:
          target: ${{ env.TEST_URL }}
          rules_file_name: '.zap/rules-config.tsv'
          cmd_options: '-a'
          allow_issue_writing: true
          fail_action: false  # Don't fail the workflow on alerts

      - name: Upload ZAP Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            report_html.html
            report_md.md
            report_json.json
          retention-days: 30
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Compile TypeScript
        run: npx tsc
        
      - name: Process ZAP Reports and Send to Prometheus
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          PROMETHEUS_PUSHGATEWAY: ${{ env.PROMETHEUS_PUSHGATEWAY }}
        # Use the compiled JavaScript file instead of the TypeScript file
        run: node dist/scripts/process-zap-reports.js