name: Test Action

on:
  pull_request:
    paths:
      - '.github/actions/synthetic-monitoring/**'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'playwright.config.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Synthetic Monitoring
        uses: ./.github/actions/synthetic-monitoring
        with:
          test_url: 'http://example.com'
          prometheus_pushgateway: 'http://localhost:9091'
          browser: 'chromium'
          test_dir: './tests'